Bug 1862794 - Use function calls instead of const val for version and channel fields in Gecko object
mozilla-mobile/relbot pull request #108
Opened 2023-11-08 21:34 UTC by gabrielluong

Changes here are needed to https://github.com/mozilla-mobile/firefox-android/pull/4346

2023-11-13 15:50 UTC, jcristau requested changes
We probably need to handle both the `const val` and the `fun` case here, because the former will still be needed on release branches after main switches to `fun`.

2023-11-13 18:21 UTC, gabrielluong commented
> We probably need to handle both the `const val` and the `fun` case here, because the former will still be needed on release branches after main switches to `fun`.

@jcristau Since we are using a tagged version of relbot in our actions https://github.com/mozilla-mobile/firefox-android/blob/main/.github/workflows/ac-update-geckoview.yml#L32, this shouldn't affect the release branches since they will be using a lower relbot version that will still function. We may also potentially be uplifting the `const val` to `fun` changes to the release branches as well based on the discussion in https://mozilla.slack.com/archives/C016PEDKY90/p1698969027616489. This will mean we will bump the relbot version in all the branches when this change lands.

2023-11-14 12:36 UTC, jcristau commented
Adding both seems reasonable to me, and means we don't have to worry about when/whether the firefox-android side of this change gets uplifted to any/all release branches.

2023-11-14 18:13 UTC, jcristau approved these changes

2023-11-14 19:10 UTC, merged